### ISSUE TITLE
Requires Python and C++ compiler to work

### ISSUE THREAD

**Issue by mattoni-cz** [bukalapak/snowboard#121]
snowboard-parser has Protagonist as required dependency, which is built using Python 2.7 and C++ build tools. This is unfortunate for environments not having these tools installed (or installed in incompatible version).
Would it be possible to use Drafter npm package instead, as recommended by Protagonist readme? It would allow pure javascript installation as a fallback to Protagonist. 
Or is there any other way, how to get it running as javascript only?
Thanks

**Comment by subosito** [comment]
We use [javascript fallback](https://github.com/bukalapak/snowboard/blob/v3/yarn.lock#L867) previously, and it has serious performance penalty and memory issue with medium to large api blueprint document, that's why we decided to drop it.

I think you can use docker or prebuilt release to use in those environments.

**Comment by mattoni-cz** [comment]
OK, thanks for quick feedback.
