### ISSUE TITLE
Non-existing row number in lint command

### ISSUE THREAD

**Issue by sheirys** [bukalapak/snowboard#28]
```
./snowboard lint -i rest.apib 
Row     |Col     |Description
--------|--------|----------------------------------------------------------------
193     |10      |action is missing a response
245     |9       |action is missing a response
254     |10      |action is missing a response
306     |9       |action is missing a response
315     |10      |action is missing a response
```

```
wc -l rest.apib 
39 rest.apib
```
My file has only 39 lines, how an error can occur on line 193, 245 etc.. ?

**Comment by subosito** [comment]
@sheirys By default snowboard show character index. To see actual row/col number you need to pass flag `-u`, eg: `./snowboard lint -u -i rest.apib`.

c83f296 fixes misleading table header as well as swap default behaviour to use row/col number instead of character index. I will push it as a part of next major release of snowboard.
