### ISSUE TITLE
Header 'Authorization' is filtered

### ISSUE THREAD

**Issue by mgonc** [bukalapak/snowboard#77]
https://github.com/bukalapak/snowboard/blob/c52a7d1904a0b19f3c22c1262559e32e63d31312/templates/winter.svelte#L114

There is a motive why this header is hidden?

**Comment by subosito** [comment]
@mgonc Because it is unused when API playground enabled, see https://github.com/bukalapak/snowboard#api-playground.

I think when API playground disabled, we can display it as is. Is it ok?

**Comment by mgonc** [comment]
Thanks fro the quick response. 
I was wondering if playground could have a custom type and pass a custom header. Like auth api that you can pass a header name and the value ia a prop editable as others headers. 
What do you think?

**Comment by subosito** [comment]
Do you have any use case for that? Currently, all headers defined in api blueprint will be available and editable except for `Authorization` header. The design decision for this is to ensure that all headers are well documented on documentation.

**Comment by IvanGuardado** [comment]
Hi all,
I've reached to here because I am on a similar situation. In our API, we are using JSON Web Tokens to authorize our private endpoints. Due to the fact the `Authorization` header is being hidden, we cannot perform custom requests using the playground console.

I don't fully understand the reason to hide it by default... Perhaps we could make it configurable?

What do you think?

**Comment by mgonc** [comment]
I made a [fork](https://github.com/mgonc/snowboard), maybe will help you.

**Comment by kingsleyh** [comment]
Looks like this has broken something in v3.6.0 - see #108

**Comment by subosito** [comment]
Now, we don't filter it; we handle it `Authorization` header differently from other headers since it's used for playground purposes. Please update snowboard to v3.7.0.
